"""empty message

Revision ID: fb961d08ef7a
Revises: 
Create Date: 2017-12-18 23:28:44.811509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb961d08ef7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('views', sa.String(length=10), nullable=True),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.Column('auth', sa.String(length=30), nullable=True),
    sa.Column('vocation', sa.String(length=30), nullable=True),
    sa.Column('video_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
